name: Welolo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "Building project. Triggered by ${{ github.event_name }} "
      - run: ./build.sh
      - run: echo "The build was a ${{ job.status }}."
      - run: echo "Running Tests"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - run: echo "Tests were a ${{ job.status }}."
