name: Welolo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "Building project. Triggered by ${{ github.event_name }} "
      - run: ./build.sh
      - run: echo "The build was a ${{ job.status }}."
      - run: echo "Starting Servers"
      - run: echo "Starting Node Server"
      - run: cd ./Welolo/
      - run: npm start &
      - run: echo "Starting React Server"
      - run: cd ./client/
      - run: npm start &
